# Config file for WGAN in gan_training.py

augconfig:
  augname: 'WGAN'
  dataset: 'ADULT'
  epochs: 3000
  seed: 0
  idn_perc: 0 # Overwritten
  has_idn: False

ganconfig:
  batchsizediv: 1
  dropout: 0.5
  gen:
    layer_nodes: [50,25,10] # hidden layers
    inneract: 'relu' # relu or sigmoid
    outputact: 'sigmoid' # sigmoid or tanh
    rmsrate: 0.0001
  disc:
    layer_nodes: [50,25,10]
    inneract: 'relu'
    outputact: 'sigmoid' # Ignored for linear
    clipval: 0.5
    rmsrate: 0.0001
    num_critic: 2

controlConfig:
  do_training: True
  do_testing: False
  plot_tsne_sample: False
  plot_loss: False
  conduct_study: False
  plot_study: False
  validate_study: False

outputconfig:
  outputdir: './output/WGAN/'
  picklename: './output/WGAN/WGANtrainingloss.p'
  synthname: './output/trainingDataBitcoinLate2012.p'
optunaconfig:
  num_tests: 10
  paramlist: [ 'self.augconfig["ganconfig"]["gen"]["rmsrate"]',
               'self.augconfig["ganconfig"]["disc"]["rmsrate"]',
               'self.augconfig["ganconfig"]["disc"]["num_critic"]',
               'self.augconfig["ganconfig"]["disc"]["clipval"]',
               'self.augconfig["ganconfig"]["gen"]["layer_nodes"][0]',
               'self.augconfig["ganconfig"]["gen"]["layer_nodes"][1]',
               'self.augconfig["ganconfig"]["gen"]["layer_nodes"][2]',
               'self.augconfig["ganconfig"]["disc"]["layer_nodes"][0]',
               'self.augconfig["ganconfig"]["disc"]["layer_nodes"][1]',
               'self.augconfig["ganconfig"]["disc"]["layer_nodes"][2]']

  params:
    genrms: [0.001, 1.0, 0.001]
    discrms: [0.001, 1.0, 0.001]
    numcritic: [1, 20, 1]
    clipval: [0.001, 1.0, 0.001]
    genlayer1: [ 25, 300, 25 ]
    genlayer2: [ 25, 300, 25 ]
    genlayer3: [ 25, 300, 25 ]
    disclayer1: [ 25, 300, 25 ]
    disclayer2: [ 25, 300, 25 ]
    disclayer3: [ 25, 300, 25 ]

