fileconfig:
  dataFile: './data/nonBlockchainData/bankmarketing.csv'
  pickleout: './output/trainingbankmarketing.p'

dataconfig:
  header: 0
  featOffset: 0
  dataname: 'BANKMARKETING'
  trainperc: 0.8
  downsample: False
  islarge: False
  numclasses: 2
  classarray: [1, 2]
  majlabel: 1
  minlabel: 2
  categoryfeatures: [1,2,3,4,5,6,7,8,9,14] # Generate automatically
  discretefeatures: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14] # Add noise to
  featureLabels: null
  ismulticlass: False