# Config file for WGAN in gan_training.py

supconfig:
  dataset: 'PIMA' # Options: CREDIT, PIMA, BANKNOTE, HABERMAN, PORTOSEGURO, THYROID
  seed: 0
  learnrate: 0.0001
  n_est: 100
  alpha1: 0.0001
  alpha2: 0.0001
  alpha3: 0.0001
  svm_c: 1.0
  eta0: 1.0
  n_est_rf: 100
  maxdepthdt: 30
  minleafdt: 2
  minsplitdt: 2
  maxdepthgb: 10
  minleafgb: 2
  minsplitgb: 2
  passagglearn: 1.0
  augmode: 'CONTROL'

controlconfig:
  do_training: False
  do_testing: False
  conduct_study: True
  plot_study: False
  plottwodim: False

outputconfig:
  outputdir: './output/SUP'
  supname: './output/SUP/1'
optunaconfig:
  sampler_seed: 0
  paramlist: [ 'self.sup_config["supconfig"]["learnrate"]',
               'self.sup_config["supconfig"]["n_est"]',
               'self.sup_config["supconfig"]["svm_c"]',
               'self.sup_config["supconfig"]["maxdepthdt"]',
               'self.sup_config["supconfig"]["minleafdt"]',
               'self.sup_config["supconfig"]["minsplitdt"]',
               'self.sup_config["supconfig"]["maxdepthgb"]',
               'self.sup_config["supconfig"]["minleafgb"]',
               'self.sup_config["supconfig"]["minsplitgb"]',
  ]
  bigparamlist: [ 'self.sup_config["supconfig"]["alpha1"]',
                  'self.sup_config["supconfig"]["alpha2"]',
                  'self.sup_config["supconfig"]["alpha3"]',
                  'self.sup_config["supconfig"]["passagglearn"]'
  ]
  params:
    learnrate: [0.0000001, 1.0, 0.00001]
    n_est: [100, 300, 100]
    svm_c: [0.01, 3.0, 0.01]
    max_depth_dt: [10,30,5]
    min_leaf_dt: [2,10,1]
    min_split_dt: [2,10,1]
    max_depth_gb: [10,30,5]
    min_leaf_gb: [2,10,1]
    min_split_gb: [2,10,1]

  bigparams:
    alpha1: [0.001, 0.1, 0.001]
    alpha2: [0.001, 0.1, 0.001]
    alpha3: [0.001, 0.1, 0.001]
    passagglearn: [0.01,2.0, 0.01]
